### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by itegulov** [levelup/Expandable-RecyclerView#1]
Can you provide an example of use, please? I tried to use it, but have got this:

02-23 21:00:28.247  31937-31937/ru.ifmo.md.lesson8 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ru.ifmo.md.lesson8, PID: 31937
    java.lang.NullPointerException: Attempt to read from field 'android.os.Parcelable com.levelupstudio.recyclerview.ExpandableRecyclerView$ExpandableAdapter.expandedStableId' on a null object reference
            at com.levelupstudio.recyclerview.ExpandableRecyclerView$ExpandableAdapter.access$2900(ExpandableRecyclerView.java:155)
            at com.levelupstudio.recyclerview.ExpandableRecyclerView.onSaveInstanceState(ExpandableRecyclerView.java:1183)
            at android.view.View.dispatchSaveInstanceState(View.java:14619)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3129)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3135)
            at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3135)
            at android.view.View.saveHierarchyState(View.java:14602)
            at android.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:1607)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:970)
            at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1187)
            at android.app.BackStackRecord.run(BackStackRecord.java:784)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
            at android.app.FragmentManagerImpl$1.run(FragmentManager.java:452)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5834)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by LOG-TAG** [comment]
@itegulov  got any other solution for ExpandableRecyclerView ?  it's a library project without sample !!

**Comment by robUx4** [comment]
Did you call `setStableIdsMode()` first ?

**Comment by fadelakin** [comment]
@robUx4 how would one go about implementing this in their project?

**Comment by johnjohndoe** [comment]
:+1: for a sample project and some basic documenation, please.

**Comment by LouisLin0706** [comment]
Good idea , can give some sample code to how to use this library~>?

**Comment by srikanth569** [comment]
Always write a sample project if you want people to use your library.

**Comment by LOG-TAG** [comment]
@srikanth569 I'm using this https://github.com/h6ah4i/android-advancedrecyclerview/tree/develop considering the expand animated view indicator !!!!  understanding the data provider takes lot of efforts!!

**Comment by moubenmao** [comment]
for a sample project and some basic documenation, please. + 1

**Comment by xitize** [comment]
why dont they just provide the way how to implement and use the code, there is also empty wiki.

**Comment by focusnews** [comment]
没有 sample project

**Comment by silviahisham** [comment]
+1 Sample project and simple documentation
